### ISSUE TITLE
Filter `reviewer` displays PRs where mentioned person is the author

### ISSUE THREAD

**Issue by barmac** [nikku/wuffle#117]
__Describe the Bug__

When I look for PRs with a specific reviewer, the task board displays also PRs created by that person.

__Steps to Reproduce__

1. Open this link: https://tasks.bpmn.io/board?s=ref%3Abpmn-io%2Fbpmn-js-properties-panel%23485
2. Notice that this issue is displayed: https://github.com/bpmn-io/bpmn-js/pull/1504

__Expected Behavior__

Only PRs where the person is a reviewer should be displayed.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Board version: [e.g. 1.0.0]

**Comment by nikku** [comment]
Thanks for reporting. Only surfaces since the recent rollout of different colors for commented and `requested_for_review`. Will look into a fix once I find the time to do so.
