### ISSUE TITLE
Indicate missing required event subscriptions and missing required permission

### ISSUE THREAD

**Issue by retog** [nikku/wuffle#145]
__Is your feature request related to a problem? Please describe__

Yes. Using [nrehwaldt/wuffle@sha256:919bd94b2192a60e5b909b7817773857af19cffb5b1177143f2265f44bd5b193](https://control.factsmission.com/#/images/sha256%3A919bd94b2192a60e5b909b7817773857af19cffb5b1177143f2265f44bd5b193) I'm getting warning messages like this:

```

WARN (wuffle:github-app): missing required permissions
    installation: "retog"
    permissions: {
      "issues": "write",
      "contents": "read",
      "metadata": "read",
      "pull_requests": "write",
      "repository_hooks": "write",
      "vulnerability_alerts": "read"
    }
WARN (wuffle:github-app): missing required event subscriptions
    installation: "retog"
    events: [
      "issues",
      "issue_comment",
      "label",
      "merge_queue_entry",
      "milestone",
      "public",
      "pull_request",
      "push",
      "repository"
    ]
```
I don't see what is missing.

__Describe the solution you'd like__

The error message should list what is missing and provide URL of documentation to learn how to fix.

__Describe alternatives you've considered__

I've considered an AI powered config wizard using quantum technology.

__Describe alternatives you've considered__

none.

**Comment by nikku** [comment]
Please use [an existing issue template](https://github.com/nikku/wuffle/issues/new/choose), providing all necessary details, including how to reproduce this + what version of `wuffle` you're using. I'll not be able to assist you otherwise.

**Comment by retog** [comment]
Added the labels of the template and completed

**Comment by nikku** [comment]
Was a quick fix: https://github.com/nikku/wuffle/commit/7e049ff90a915183fef8cbfd62c85d70ffc00447.
