### ISSUE TITLE
Removed pull request is not removed from the board

### ISSUE THREAD

**Issue by barmac** [nikku/wuffle#216]
### Describe the Bug

The pull request in the inbox was removed from GitHub, and the link is now dead (404):

![image](https://github.com/user-attachments/assets/4daccdd1-8438-4802-9f11-5fc4a7e74cc0)

Yet, the PR is stuck in our board, and you can see that in the link:

https://tasks.bpmn.io/board?c=%21Inbox&s=repo%3A%22bpmn-io%2Fdmn-js-properties-panel%22+

The pull request can be moved to another column, but then the UI reports an error. The card stays in the column though.

https://github.com/user-attachments/assets/ff0751b9-23ac-419f-b7ed-bef9539c8c8d

For more context, the PR was created by an AI-spam-service. So it was probably removed by some GH spam filter.

### Steps to Reproduce

Create a pull request, remove it, and check the board.

### Expected Behavior

Pull request is removed from the board.

### Environment

https://tasks.bpmn.io

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Board version: [e.g. 1.0.0]

**Comment by nikku** [comment]
Pull requests cannot be removed using the standard GitHub interface. So how did you do it?

![screenshot LHX9RL](https://github.com/user-attachments/assets/a5cabcb5-81c1-4c51-9924-6680741b07cd)

**Comment by nikku** [comment]
Did you ask GitHub staff to [delete the pull request](https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github)? If so, why?

This tools operates on [standard GitHub events](https://docs.github.com/en/webhooks/webhook-events-and-payloads) and API, I'm afraid it cannot simply compensate for _internal_ maintainance operations.

**Comment by nikku** [comment]
I shipped a fix via https://github.com/nikku/wuffle/pull/218 and will test this one, if it works we're lucky, otherwise manual data maintainance is needed to fix this edge case.

**Comment by nikku** [comment]
You may update to [`v0.63.1`](https://github.com/nikku/wuffle/blob/main/packages/app/CHANGELOG.md#0631) and see if it solves your issue.

**Comment by barmac** [comment]
> Did you ask GitHub staff to [delete the pull request](https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github)? If so, why?
> 
> This tools operates on [standard GitHub events](https://docs.github.com/en/webhooks/webhook-events-and-payloads) and API, I'm afraid it cannot simply compensate for _internal_ maintainance operations.

I did not! But it's not there.
