### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by adamdougal** [nikku/wuffle#25]
Heya, thanks for creating this great Waffle replacement!

Would it be possible for this repo to also provide a Dockerfile? Or even better, a Docker image published to the Docker hub?

Happy to contribute :)

**Comment by nikku** [comment]
I have no bandwidth to create a Dockerfile but I can absolutely understand what you're getting at.

Could you file a PR that adds a docker file in a `support` directory. We can use that PR to discuss what the file should actually accomplish and add it to the docs afterwards, once ready.

That would be amazing.

**Comment by adamdougal** [comment]
https://github.com/nikku/wuffle/pull/26

**Comment by nikku** [comment]
Closed via https://github.com/nikku/wuffle/commit/837a3211b69616d11044c24cf2cdbee48fe1e079.

**Comment by adamdougal** [comment]
Awesome thanks @nikku :)
