### ISSUE TITLE
Display number of completed child issues in parent issues

### ISSUE THREAD

**Issue by adamdougal** [nikku/wuffle#27]
Heya, would you be open to displaying a issue completed counter with a progress bar for `parent of`/`child of` links? 

Basically how Waffle used to show them:
![Screen Shot 2019-06-27 at 10 53 34](https://user-images.githubusercontent.com/1589887/60354764-dfddb700-99c4-11e9-81f2-a69ed247cfff.png)

Obviously happy to contribute!

**Comment by nikku** [comment]
I'm open for contributions that implement such improvement.

**Comment by nikku** [comment]
Implemented this as an epic progress bar via https://github.com/nikku/wuffle/commit/01646526e823219bbacd93a60c0f35769c8eb6ea, similar to how GitHub shows completed tasks on issues.

![capture IwWlaV_optimized](https://user-images.githubusercontent.com/58601/61170860-7d151f80-a56f-11e9-9c2e-b02adfe0ac4d.gif)

**Comment by adamdougal** [comment]
Awesome thanks! Sorry I didn't get around to contributing this myself :(
