### ISSUE TITLE
Treat all PR links the same as fixes

### ISSUE THREAD

**Issue by adamdougal** [nikku/wuffle#28]
Heya, at the moment when raising a PR that `fixes` an issue, the issue is pulled across to the `Needs Review` column and not shown anywhere else e.g:

![Screen Shot 2019-07-01 at 13 47 54](https://user-images.githubusercontent.com/1589887/60438025-97faa200-9c07-11e9-8c19-e05512cfcc57.png)

If it has any other relationship type, e.g. `Required by`, `Depends on` etc, the issue remains where it is with the PR below it and the PR appears in the `Needs Review` column with the issue below it e.g.

![Screen Shot 2019-07-01 at 13 49 39](https://user-images.githubusercontent.com/1589887/60438334-5d453980-9c08-11e9-84f4-301a8345b374.png)
![Screen Shot 2019-07-01 at 13 58 41](https://user-images.githubusercontent.com/1589887/60438335-5dddd000-9c08-11e9-83ff-b032df39d8e9.png)

Would you be open to make all link types behave the same as `fixes`? The advantage then being that the issues and pr's are only shown once rather then twice. It also makes this the same as what Waffle used to do.

Also, once the PR has been merged/closed, we could make the issues return to the `In Progress` column.

**Comment by nikku** [comment]
Agreed on the fact that PRs should always be collapsed under the issue rather than appearing as embedded links :+1:.

Not sure about moving an issue if the state of a non-closing linked PR changes. If you got a couple of `Related to #someIssue` links from different PRs, would you expect the issue to move into the review column, each time one of these PRs is put into review? I'd rather expect the issue remains where it is and that the linked PRs appear separated on the boards needs review column.

**Comment by nikku** [comment]
Implemented that all linked PRs are always shown collapsed under the given card:

![image](https://user-images.githubusercontent.com/58601/60744848-0cbb3c80-9f78-11e9-82a5-6ede16925ff1.png)

Note that issues and PRs (`83` in the screenshot) are still shown in the review column as a separate card. From my point of view, this is already an improvement.

**Comment by nikku** [comment]
One improvement to consider here could be to not show PR cards, if these PRs are already attached to issues in the same column. That gives users the freedom to move issue + PR around and benefit from no card duplication in the standard cases.

**Comment by nikku** [comment]
Happy to hear your feedback on this.

**Comment by joannenolan-sky** [comment]
yes, that is done. I just need to rebase my branch which has those changes already
________________________________
