### ISSUE TITLE
Docker: Store local data on host rather than in container

### ISSUE THREAD

**Issue by retog** [nikku/wuffle#47]
When updating the docker image one looses the order of the cards. If the Readme for the Docker-File would instruct to mount the folder where this data is stored from the host, this could be avoided.

**Comment by nikku** [comment]
There exists [two kinds of storage](https://github.com/nikku/wuffle/tree/master/packages/app/lib/apps/dump-store), `local` and `s3`. I was not aware of the fact that people use local store in production setups.

If you have an idea how to improve the existing documentation in this aspect, go for it. I'm happy to take contributions that clarify this.

**Comment by retog** [comment]
I had no idea that two kind of storage exist. Don't see anything about it in https://github.com/nikku/wuffle/blob/master/docs/SETUP.md.

Currently when starting the container with docker-compose I mount the config as a volume:

```
volumes:
      - ./wuffle/wuffle.config.js:/app/packages/app/wuffle.config.js
```

I was thinking I could mount the folder where wuffle stores data in just the same way.

**Comment by nikku** [comment]
Yes, that is an option that could be documented somewhere.

**Comment by nikku** [comment]
Storage [is now documented](https://github.com/nikku/wuffle/blob/master/docs/STORAGE.md).

People good at Docker will surely know how to map that file.
