### ISSUE TITLE
Change in Column Name not picked up

### ISSUE THREAD

**Issue by joannenolan-sky** [nikku/wuffle#49]
in `wuffle-config.js`, I renamed `Next` to` To Do`. 
On restart, all issues in that column did not appear.  When I checked they were still under the Next Column in the `storedump.json` and did not appear at all, as a column rename is not picked up to ensure the column exists on restart

To fix the issue I had to remove the label on each issues and re add to get it to appear correctly

**Comment by nikku** [comment]
Not sure how to circumvent this issue. A few options:

* Do not support renaming in populated boards
* Recognize column renamings and move items on re-start (that would require to persist the current configuration within the storedump)
* Provide a way to update the storedump before restarting the app

Any thoughts?

**Comment by joannenolan-sky** [comment]
Hmm maybe check if the column is valid/exists on background sync and if not remove it and get valid column for label

**Comment by nikku** [comment]
Shipped with `v0.27.0`.
