### ISSUE TITLE
[HELP] Install Issue

### ISSUE THREAD

**Issue by mzch** [nikku/wuffle#51]
Hi,

I tried to install wuffle. I installed Github app and modified .env, but whenever restarting wuffle, it will always show 'Getting Started' page. What's the matter?

-- .env
```
APP_ID=43251
PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n"
WEBHOOK_PROXY_URL=https://smee.io/SjfMBN0wikQy66q2
WEBHOOK_SECRET=xxxxxx
GITHUB_CLIENT_ID=xxxxxx
GITHUB_CLIENT_SECRET=xxxxxx
SESSION_SECRET=xxxxxx
BASE_URL=https://githubstate.com
LOG_LEVEL=debug
```
Github app settings is below:
https://d.pr/i/hx6FTj

**Comment by nikku** [comment]
Please provide the following information:

* full setup steps
* where you added / edited which files
* application log from startup

Thanks.

**Comment by mzch** [comment]
- full setup step
  - clone repository
  - npm install
  - npm run dev & Create Github app via Setup page (probot)
  - interrupt avobe command.
  - edit .env & wuffle.config.js
  - create systemd startup unit file (use 'node bin/run.js)
- where you added / edited which files
  - edited: .env
  - added: wuffle.config.js
- application log
```
Oct  9 12:42:00 n24 systemd[1]: Started Wuffle - Guthub Issue board.
Oct  9 12:42:00 n24 node[23784]: 19:42:00.517Z  INFO wuffle:run: Validating configuration
Oct  9 12:42:00 n24 node[23784]: 19:42:00.522Z  INFO wuffle:run: Starting Wuffle v0.24.1
Oct  9 12:42:00 n24 node[23784]: Warning: connect.session() MemoryStore is not
Oct  9 12:42:00 n24 node[23784]: designed for a production environment, as it will leak
Oct  9 12:42:00 n24 node[23784]: memory, and will not scale past a single process.
Oct  9 12:42:00 n24 node[23784]: 19:42:00.608Z  INFO probot:
Oct  9 12:42:00 n24 node[23784]:
Oct  9 12:42:00 n24 node[23784]:   Welcome to Probot! Go to http://localhost:3000 to get started.
Oct  9 12:42:00 n24 node[23784]:
Oct  9 12:42:00 n24 node[23784]: 19:42:00.700Z  INFO probot: Forwarding https://smee.io/SjfMBN0wikQy66q2 to http://localhost:3000/
Oct  9 12:42:00 n24 node[23784]: 19:42:00.703Z  INFO probot: Listening on http://localhost:3000
Oct  9 12:42:01 n24 node[23784]: 19:42:01.007Z  INFO probot: Connected https://smee.io/SjfMBN0wikQy6
Oct  9 12:43:34 n24 node[23784]: 19:43:34.956Z  INFO http: GET / 302 - 9.07 ms (id=8c1ef878-4c89-413b-b1c4-b5cab436afd8)
Oct  9 12:43:35 n24 node[23784]: 19:43:35.184Z  INFO http: GET /probot 200 - 83.81 ms (id=bb2d4055-a774-4290-8eb1-3c8f69eb04ff)
Oct  9 12:43:35 n24 node[23784]: 19:43:35.375Z  INFO http: GET /primer.css 200 - 18.13 ms (id=02b1cf46-e505-485a-b4a3-13db4fa40db7)
Oct  9 12:43:35 n24 node[23784]: 19:43:35.378Z  INFO http: GET /robot.svg 200 - 12.71 ms (id=37ca2319-8b76-4e70-b5c5-0d47748bfeda)
Oct  9 12:44:25 n24 node[23784]: 19:44:25.452Z  INFO http: GET / 302 - 0.95 ms (id=67d9c1fa-65da-4d3e-9d81-3fc071c2a560)
Oct  9 12:44:25 n24 node[23784]: 19:44:25.608Z  INFO http: GET /probot 200 - 7.67 ms (id=d121c551-54d8-45f0-bff5-dcf15cf7f4fb)
Oct  9 12:44:25 n24 node[23784]: 19:44:25.767Z  INFO http: GET /robot.svg 304 - 3.26 ms (id=c4a96729-46d7-4dae-8f43-d948b5b8523f)
Oct  9 12:44:25 n24 node[23784]: 19:44:25.770Z  INFO http: GET /primer.css 200 - 8.24 ms (id=49df08b4-e08b-4338-8b4e-109bb29bd710)
 ```

**Comment by nikku** [comment]
Where did you create the configuration files? They have to reside in the [`app`](https://github.com/nikku/wuffle/tree/master/packages/app) directory.

**Comment by nikku** [comment]
As an additional note, you must execute `npm run all` once before being able to run the app in production mode (via `npm start`).

**Comment by mzch** [comment]
Great! Everything went well! Please add those steps to SETUP.md.

**Comment by nikku** [comment]
It is part of the instructions already, cf. [this section](https://github.com/nikku/wuffle/blob/master/docs/SETUP.md#manual-steps). 

If you find a way to improve the instructions, please file a pull request.

**Comment by mzch** [comment]
Well, it seems to lack 'execute `npm run all`'...

**Comment by nikku** [comment]
Aha, that's what was missing. I'll improve the validation regarding this.

**Comment by nikku** [comment]
Improved validation via https://github.com/nikku/wuffle/commit/05e45adc335a76f339414c53d5eabb1f912895ad. Thanks for your feedback :heart_eyes:
