### ISSUE TITLE
Show labels of issues when added to custom columns

### ISSUE THREAD

**Issue by jjlankinen** [nikku/wuffle#67]
__Is your feature request related to a problem? Please describe.__

It would be beneficial to be able to see labels of issues that are configured to be placed in custom columns.

Below is example of some sort of board configuration that has 2 custom columns defined to be populated with issues with custom labels. Columns are _Needs Grooming_ populated with issues that has label **groom** and _Bugs_ populated with issues that has label **bug**:
```
module.exports = {
  name: 'Test Board',
  columns: [
    { name: 'Inbox', label: null, sorting: true, states: [ 'DEFAULT', 'EXTERNAL_CONTRIBUTION' ] },
    { name: 'Needs Grooming', label: 'groom', sorting: true },
    { name: 'Bugs', label: 'bug', sorting: true },
    { name: 'In Progress, label: 'IN PROGRESS', sorting: true, states: [ 'IN_PROGRESS' ] },
    { name: 'Needs Review', label: 'NEEDS REVIEW', sorting: true, states: [ 'IN_REVIEW' ] },
    { name: 'Done', label: null, closed: true, sorting: true, states: [ 'DONE' ] }
  ]
};
```
Currently cards showed in the board has those **bug** and **groom** labels omitted. As an UI/UX designer and being a team lead who mostly uses kanban board to see visually github issues placed in meaningful columns it's been easier for me (as well as others) to see issues with recognizable labels (via colors) without the need to actually read the column label and the label for the column might not always be the same as the label's name. I could easily assign multiple labels to be placed to same column because reasons.

__Describe the solution you'd like__

If possible there could be another option added that will allow custom issues labels to be visible. This option does not have to be available to columns that have states defined as it might be redundant to show NEED REVIEW label etc. in those cases.

Suggestion (naming convention might not follow the correct rules):
```
module.exports = {
  name: 'Test Board',
  columns: [
    { name: 'Inbox', label: null, sorting: true, states: [ 'DEFAULT', 'EXTERNAL_CONTRIBUTION' ] },
    { name: 'Needs Grooming', label: 'groom', sorting: true, showLabel: true },
    { name: 'Bugs', label: 'bug', sorting: true, showLabel: true },
    { name: 'In Progress, label: 'IN PROGRESS', sorting: true, states: [ 'IN_PROGRESS' ] },
    { name: 'Needs Review', label: 'NEEDS REVIEW', sorting: true, states: [ 'IN_REVIEW' ] },
    { name: 'Done', label: null, closed: true, sorting: true, states: [ 'DONE' ] }
  ]
};
```
With those extra options added then issues placed in _Bugs_ and _Needs Grooming_ column would show labels. 

If by any reason someone would like to group **groom** and **bug** labeled issues under single column that has title _Needs fixing and grooming_ it would be hard to say which issue is bug and which is to be groomed etc.

__Describe alternatives you've considered__

Just suck it up and try to set the board differently, not optimal but possibility of course.

**Comment by joannenolan-sky** [comment]
We had a similar issue, we wanted a bug column but we didn't want the bug label to be removed when the issue was picked up. To get around this we created a `next-bug` label which allows the label to be shown but the label will be removed as the issue goes through the automatic dev flow. This is especially useful as a board can get quite cluttered if there are a lot of labels

**Comment by nikku** [comment]
Thansk @joannenolan-sky for sharing your feedback regarding this feature request.

Given the fact that you can create a next-bug label from the bug label on GitHub I'm actually inclined to close this PR as _wontfix_.

**Comment by jjlankinen** [comment]
Well that's unfortunate to hear.

**Comment by nikku** [comment]
Closing this one as indicated a year ago.
