### ISSUE TITLE
Support github's full array of closing keywords

### ISSUE THREAD

**Issue by jjlankinen** [nikku/wuffle#71]
__Is your feature request related to a problem? Please describe.__

Currently Wuffle board only supports 2 Github's closing keywords which are _closes_ and _fixes_ and it would be nice to actually get this board to integrate into the Github better by adding support for the rest of the keywords also.

__Describe the solution you'd like__

I would like to see every Github's closing keywords supported which are described here: https://help.github.com/en/articles/closing-issues-using-keywords

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

__Describe alternatives you've considered__

If this is too much of work and it's decided not to follow full keyword support then alternative is to force team members and collaborators to suck it up and force them to change their keyword usage habits which can be a bit problematic as unknown collaborators need to know which keywords can be used.

**Comment by nikku** [comment]
I'm fine supporting the full range of closing keywords. :+1:

**Comment by nikku** [comment]
I personally don't like the `connects` and `connected to` it is highly ambiguous.

For the closes hints, I'm happy to accept a PR that contributes the improvements.

**Comment by nikku** [comment]
> Waffle also support connects to and connected to for a parent-child relationship.

I reconsidered my opinion here. The keywords are cryptic enough so that they probably do not cause confusion. Likely no-one except for a former Waffle user are using these. If they matter to you, file a PR and I'll accept it as a contribution.

**Comment by nikku** [comment]
Released with `v0.28.0`. Special thanks to @mjcarroll for contributing this improvement.
