### ISSUE TITLE
Exclude archived repository

### ISSUE THREAD

**Issue by retog** [nikku/wuffle#79]
__Is your feature request related to a problem? Please describe.__

Problem: currently we see issues from archived repository, as one cannot resolve issues in a read-only repo this makes little sense.

__Describe the solution you'd like__

Archived repositories should be ignored.

__Describe alternatives you've considered__

There could also be an ignore-list in the config if one wants to enable wuffle for all current and future reposiries except a few.

**Comment by nikku** [comment]
Makes absolute sense. Would you like to contribute this feature?

**Comment by retog** [comment]
Actually I see myself more as fan and issue contributor as my limited resources are overstreched with other open source projectes. I nevertheless gave it a quick glance and it seems like it's already there!

https://github.com/nikku/wuffle/blob/374563a73eb95e6095bbeef2c4a8c4afaa4b809e/packages/app/lib/apps/background-sync/BackgroundSync.js#L114

Maybe I've been using an outdated image? Sorry for that.

**Comment by nikku** [comment]
Thanks for reporting. I was not sure if I added it. :bulb:
