### ISSUE TITLE
Unable to Filter by Label when Using Emojis

### ISSUE THREAD

**Issue by theportablegeek** [nikku/wuffle#87]
__Describe the Bug__

When using emojis in your labels (such as with [Bookstack](https://github.com/BookStackApp/BookStack/labels)) you are unable to filter by label.

__Steps to Reproduce__

1. Create a New Label which includes an Emoji
2. Open Wuffle
3. Attempt to Filter by Label

__Expected Behavior__

That the filter function would work.

__Environment__

- Host (Browser/Node version), if applicable: Heroku
- OS: Windows 10
- Board version: v0.34.0

**Comment by nikku** [comment]
Could you elaborate what you expect?

* I created a label `:art: Design`
* The label is shown via auto completion
* The label _filters_, if selected

I do not see where the bug is.

**Comment by nikku** [comment]
The issue that obviously exists is that these labels are not properly rendered.

I'd expect rendering such as :art: Design but get `:art: Design`.

**Comment by theportablegeek** [comment]
@nikku do you still need further explanation?

**Comment by nikku** [comment]
Yes, cf. https://github.com/nikku/wuffle/issues/87#issuecomment-645014873.

The filter function works, as stated in my comment. What would you expect to work in addition?
