### ISSUE TITLE
Update 2 events as they are being deprecated/renamed

### ISSUE THREAD

**Issue by joannenolan-sky** [nikku/wuffle#88]
__What should we do?__

We're contacting you regarding upcoming changes for your GitHub Apps:

  - test-wuffle

We no longer support two events which your GitHub Apps may rely on, "integration_installation" and "integration_installation_repositories".

These events can be replaced with the "installation" and "installation_repositories" events respectively.

The "integration_installation" and "integration_installation_repositories" events will be removed after October 1st, 2020.

__Why should we do it?__

It will stop working correctly for creating a new wuffle instance

**Comment by nikku** [comment]
I've received that notification as well. Could you look into where the events are actually being used? Is it Probot that needs upgrading?

**Comment by nikku** [comment]
As the message suggests, we _may_ use these events:

> We no longer support two events which your GitHub Apps may rely on, "integration_installation" and "integration_installation_repositories".

However, from what I understand we don't. The message went to all GitHub app owners (I've received the warning for all my GitHub apps, so this is more of a friendly hint for app owners to check. Closing this, as now work is needed.
