### ISSUE TITLE
Is Wuffle still working / alive in any form?

### ISSUE THREAD

**Issue by Tectract** [nikku/wuffle#89]
Can I still pull the latest code and run it on my own servers? 

I was sad to see the project website go down, maybe I can help revive it :)

**Comment by nikku** [comment]
Wuffle is working, absolutely. Give it a try.

**Comment by nikku** [comment]
As a side note, nothing changed though fundamentally since [last time you tried](https://github.com/nikku/wuffle/issues/43).
