### ISSUE TITLE
Filter transferred issues (so to not display them twice)

### ISSUE THREAD

**Issue by MaxTru** [nikku/wuffle#90]
__Describe the feature / what is the problem?__

Once an issue is transferred from a repo to another, it is displayed twice in the wuffle board. 
![Screenshot_20201014_105359](https://user-images.githubusercontent.com/42800119/95966560-91e40100-0e0b-11eb-8349-18c811fa0112.png)

In detail:
The original issue URI is still valid (e.g., https://github.com/bpmn-io/fake-join/issues/22) but will redirect to the new issue (https://github.com/bpmn-io/internal-docs/issues/178). The old issue cannot be found in the issues of the original repo (https://github.com/bpmn-io/fake-join/issues/). So it seems like that GitHub simply still provides the reference to the issue on API level. 

Probably we need to decide whether this is a bug or a feature. IMO we should filter transferred issues. 

__Steps to Reproduce__

1. Transfer an issue to a new repo which is also in scope of the respective wuffle instance
2. Two cards will appear on wuffle both referencing (effectively) the same issue

__Environment__

- Host (Browser/Node version), if applicable: Brave (Chromium-based)
- OS: Arch Manjaro Linux
- Board version: 0.34.0

**Comment by nikku** [comment]
Apparently there is a `transferred` event that we do not integrate with, yet: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
